version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: library_db_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_password
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: